version: 2.1
jobs:
  build:
    docker:
      - image: avm007/eosio.cdt:latest
    steps:
      - checkout
      - run:
          name: "Build contract and unit tests"
          command: |
            mkdir -p build
            cd build
            cmake -DBUILD_TESTS=true ..
            make
      - run:
          name: "Run unit tests"
          command: make test